services:
  icecast:
    image: infiniteproject/icecast-kh
    container_name: icecast
    restart: always
    environment:
      - ICECAST_SOURCE_PASSWORD=mistream
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
      - ICECAST_HOSTNAME=localhost
    ports:
      - "8000:8000"
    volumes:
      - ./config/icecast.xml:/etc/icecast.xml
    networks:
      - radio-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./widget.html:/usr/share/nginx/html/widget.html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - icecast
    networks:
      - radio-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - radio-net

networks:
  radio-net:
    driver: bridge
